<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="atrv">

<!-- Some Color Materials -->
  <material name="Green"><color rgba="0.0 0.8 0.0 1.0"/></material>
  <material name="Red"><color rgba="0.8 0.0 0.0 1.0"/></material>
  <material name="White"><color rgba="1.0 1.0 1.0 1.0"/></material>
  <material name="Blue"><color rgba="0.0 0.0 0.8 1.0"/></material>
  <material name="Black"><color rgba="0.0 0.0 0.0 1.0"/></material>
  <material name="Grey"><color rgba="0.7 0.7 0.7 0.7"/></material>
  <material name="atrv_orange"><color rgba="0.8 0.16 0.0 1" /></material>
  <material name="clear"><color rgba="0 0 0 0"/></material>

<!-- xacro parameters -->
  <xacro:property name="M_PI" value="3.14159"/>
  <!-- Robot parameters -->
  <xacro:property name="ground_clearance" value="0.13" />
  <!-- This is not including the bumpers -->
  <xacro:property name="chassis_length" value="0.83" />
  <!-- This is including the bumpers -->
  <xacro:property name="chassis_length_bumpers" value="1.02" />
  <!-- This is not including the wheels -->
  <xacro:property name="chassis_width" value="0.46" />
  <!-- This is not including equipment and racks on the top -->
  <xacro:property name="chassis_height" value="0.50" />
  <xacro:property name="wheel_radius" value="0.20"/>
  <xacro:property name="wheel_width" value="0.15"/>

<!-- xacro macros -->
  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0"
               iyy="1.0" iyz="0.0"
               izz="1.0" />
      </inertial>
  </xacro:macro>

<!-- links -->
  <!-- base_footprint -->
  <!-- The frame of the floor directly below the base_link and -->
  <!-- is needed for the navigation stack to work properly -->
  <link name="base_footprint"></link>

  <!-- base_link -->
  <!-- The link that is the origin of all of the components of the -->
  <!-- robot and should also represent the main chassis via inertial, -->
  <!-- visual, and geometry elements of the link -->
  <link name="base_link">
    <xacro:default_inertial mass="80"/>

    <visual>
      <geometry>
        <mesh filename="package://gavlab_atrv_description/meshes/atrv_chassis.dae"/>
      </geometry>
      <!-- <material name="clear"/> -->
    </visual>

    <collision>
      <origin xyz="0 0 ${chassis_height/2.0}" rpy="0 0 0" />
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
      </geometry>
    </collision>
  </link>

  <!-- base_footprint -> base_link -->
  <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${ground_clearance}" rpy="0 0 0"/>
      <parent link="base_footprint"/>
      <child link="base_link"/>
  </joint>

  <!-- This is a macro for the links that describe the wheels -->
  <xacro:macro name="wheel" params="prefix reflect_x reflect_y">
    <link name="${prefix}_wheel_link">
      <xacro:default_inertial mass="1"/>

      <visual>
        <origin xyz="0 0 ${wheel_width/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Black"/>
      </visual>

      <collision>
        <origin xyz="0 0 ${wheel_width/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <!-- base_link -> ${prefix}_wheel_link -->
    <joint name="${prefix}_wheel_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="${(chassis_length/2 - wheel_radius)*reflect_x} ${(chassis_width/2 + 0.03)*reflect_y} ${wheel_radius - ground_clearance}"
              rpy="${(M_PI/2)*reflect_y*-1} 0 0"/>
    </joint>
  </xacro:macro>

  <!-- left_front_wheel_link -->
  <xacro:wheel prefix="left_front" reflect_x="1" reflect_y="1" />
  <!-- left_rear_wheel_link -->
  <xacro:wheel prefix="left_rear" reflect_x="-1" reflect_y="1" />
  <!-- right_front_wheel_link -->
  <xacro:wheel prefix="right_front" reflect_x="1" reflect_y="-1" />
  <!-- right_rear_wheel_link -->
  <xacro:wheel prefix="right_rear" reflect_x="-1" reflect_y="-1" />

  <!-- Imu Link -->
  <link name="imu_frame"/>

  <joint name="base_imu_joint" type="fixed">
    <origin xyz="-0.11 0 0.27" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="imu_frame"/>
  </joint>

  <!-- laser_link -->
  <xacro:property name="laser_radius" value="0.045"/>
  <xacro:property name="laser_height" value="0.16"/>
  <link name="laser_link">
    <xacro:default_inertial mass="3"/>

    <visual>
      <origin xyz="0 0 ${0.04-laser_height/2.0}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_height}"/>
      </geometry>
      <material name="Grey"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${0.04-laser_height/2.0}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- base_link -> laser_link -->
  <joint name="base_laser_joint" type="fixed">
    <origin xyz="${0.015+laser_radius+chassis_length/2.0} 0 ${0.28-ground_clearance}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="laser_link"/>
  </joint>

  <!-- kinect_link -->
  <link name="asus_link">
    <xacro:default_inertial mass="0.0001"/>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://gavlab_atrv_description/meshes/kinect.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.0730 0.2760 0.0720"/>
      </geometry>
    </collision>
  </link>

  <!-- base_link -> base_kinect_join -->
  <joint name="base_kinect_joint" type="fixed">
  <!-- <joint name="base_kinect_joint" type="planar"> -->
    <origin xyz="${(chassis_length/2)-0.229} 0 ${chassis_height+0.092}" rpy="0 0 0"/>
    <!-- <axis xyz="0 0 1"/> -->
    <!-- <limit effort="1" velocity="1" lower="-1" upper="1" /> -->
    <parent link="base_link"/>
    <child link="asus_link"/>
  </joint>

</robot>